<?php
/*
*Created by juno
*/
?>
<div class="account-create hatton">
    <h1><?php echo $this->__('New Account') ?></h1>
    <?php echo $this->getChildHtml('form_fields_before') ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="hatton-form">
            <div class="margin1">
                <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>"/>
                <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>"/>

                <h2><?php echo $this->__('Personal Information') ?></h2>
                <ul class="form-list">
                    <li>
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                    </li>
                    <li>
                        <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" name="email" id="email_address"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
                                   title="<?php echo $this->__('Email Address') ?>"
                                   class="input-text validate-email required-entry"/>
                        </div>
                    </li>
                    <?php if ($this->isNewsletterEnabled()): ?>
                        <li class="control">
                            <div class="input-box">
                                <input type="checkbox" name="is_subscribed"
                                       title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1"
                                       id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                                       class="checkbox"/>
                            </div>
                            <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                        </li>
                    <?php endif ?>
                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php if ($_dob->isEnabled()): ?>
                        <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                        <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                    <?php endif ?>
                </ul>
                <h2><?php echo $this->__('Login Information') ?></h2>
                <ul class="form-list">
                    <li>
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                        <div class="input-box">
                            <input type="password" name="password" id="password"
                                   title="<?php echo $this->__('Password') ?>"
                                   class="input-text required-entry validate-password"/>
                        </div>
                    </li>
                    <li>
                        <label for="confirmation"
                               class="required"><em>*</em><?php echo $this->__('Confirm Password') ?>
                        </label>

                        <div class="input-box">
                            <input type="password" name="confirmation"
                                   title="<?php echo $this->__('Confirm Password') ?>" id="confirmation"
                                   class="input-text required-entry validate-cpassword"/>
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                <button class="hatton-button" type="submit" title="<?php echo $this->__('Submit') ?>">
                    <span><span><?php echo $this->__('Create an account') ?></span></span></button>
                <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                    <input name="context" type="hidden" value="checkout"/>
                <?php endif; ?>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
        //]]>
    </script>
</div>
